[package]
name = "denester"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]

[features]
test-utils = []

[[test]]
name = "schema"
harness = true
required-features = ["test-utils"]

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
